/**
 * E2E encryption for room links.
 *
 * ## Key derivation — no raw private key available
 *
 * The Deno sandbox a link language runs in never exposes the agent's raw
 * Ed25519 private key material — the only signing primitive available via
 * `ad4m:host` is `agentSignStringHex(payload)`, a black-box "sign this for
 * me" call (see src/adapters.ts AgentAdapter). So this module cannot do the
 * textbook `edwardsToMontgomery` conversion from a raw Ed25519 scalar.
 *
 * Instead it derives a stable, secret X25519 keypair from the agent's
 * signing capability itself: Ed25519 (EdDSA) signatures are deterministic
 * (RFC 8032 — no randomness is mixed in), so signing one fixed,
 * domain-separated message always reproduces the exact same signature
 * bytes for a given DID. That signature is only computable by whoever
 * controls the private key, so `sha256(sign(FIXED_MESSAGE))` behaves as a
 * secret, deterministic 32-byte value unique to this agent — exactly the
 * key material an X25519 private scalar needs. Nobody else can derive it
 * without the agent's cooperation (via the host's signing service).
 *
 * The corresponding X25519 *public* key is computed the normal way
 * (scalar multiplication with the base point) and is safe to publish.
 * Because there is no dedicated "register my E2E public key" endpoint in
 * the link-server API this language targets, the public key is
 * piggybacked onto the second step of the DID challenge-response auth
 * flow (see src/auth.ts) as an additive `x25519PublicKey` field — the
 * natural point where the agent already proves DID ownership to the
 * server.
 *
 * ## Room key distribution — sealed box
 *
 * `GET /rooms/:roomId/keys` returns the room's shared AES-256-GCM key,
 * already wrapped for the calling agent as a sealed box: an ephemeral
 * X25519 keypair is generated by whoever sealed the key, ECDH'd against
 * the recipient's static X25519 public key, and the shared secret (via
 * HKDF-SHA256) becomes the AES-256-GCM key that wraps the room key. Only
 * the ephemeral public key travels in the envelope — the recipient
 * recomputes the same shared secret using their own static private key,
 * exactly like libsodium's `crypto_box_seal`.
 *
 * ## Link confidentiality
 *
 * Once a room key is available, `encryptLinkForWire` / `decryptLinkFromWire`
 * protect the ENTIRE LinkExpression (author, timestamp, proof, and data)
 * crossing the wire. No metadata leaks — the server only sees ciphertext
 * plus a client-computed `link_hash` for OR-Set dedup. The local store
 * always holds decrypted links (see src/sync.ts); only the wire
 * representation is ciphertext.
 *
 * `decryptLinkFromWire` handles both the current full-encryption format and
 * the legacy data-only format (for backward compatibility with links
 * encrypted before the full-encryption change).
 */

import { x25519 } from "@noble/curves/ed25519";
import { gcm } from "@noble/ciphers/aes";
import { sha256 } from "@noble/hashes/sha2";
import { hkdf } from "@noble/hashes/hkdf";

import type {
    KeysResponseEntry,
    Link,
    LinkExpression,
    SealedRoomKeyEnvelope,
    WireLinkExpression,
} from "./types.js";
import { isEncryptedLinkData } from "./types.js";

// ---------------------------------------------------------------------------
// Domain separation constants
// ---------------------------------------------------------------------------

const X25519_SEED_MESSAGE = "adam-server-link-language:x25519-seed:v1";
const ROOM_KEY_SEAL_INFO = "adam-server-link-language:room-key-seal:v1";

export const AES_KEY_BYTES = 32; // AES-256
export const AES_NONCE_BYTES = 12; // standard GCM nonce size
export const X25519_KEY_BYTES = 32;

// ---------------------------------------------------------------------------
// Byte / hex helpers
// ---------------------------------------------------------------------------

export function bytesToHex(bytes: Uint8Array): string {
    let out = "";
    for (let i = 0; i < bytes.length; i++) {
        out += bytes[i].toString(16).padStart(2, "0");
    }
    return out;
}

const HEX_PAIR = /^[0-9a-fA-F]{2}$/;

export function hexToBytes(hex: string): Uint8Array {
    const clean = hex.trim();
    if (clean.length % 2 !== 0) {
        throw new Error(`hexToBytes: odd-length hex string (${clean.length} chars)`);
    }
    const out = new Uint8Array(clean.length / 2);
    for (let i = 0; i < out.length; i++) {
        const byte = clean.substring(i * 2, i * 2 + 2);
        if (!HEX_PAIR.test(byte)) {
            throw new Error(`hexToBytes: invalid hex byte "${byte}" at offset ${i * 2}`);
        }
        out[i] = parseInt(byte, 16);
    }
    return out;
}

function utf8ToBytes(str: string): Uint8Array {
    return new TextEncoder().encode(str);
}

function bytesToUtf8(bytes: Uint8Array): string {
    return new TextDecoder().decode(bytes);
}

function concatBytes(...chunks: Uint8Array[]): Uint8Array {
    const total = chunks.reduce((sum, c) => sum + c.length, 0);
    const out = new Uint8Array(total);
    let offset = 0;
    for (const chunk of chunks) {
        out.set(chunk, offset);
        offset += chunk.length;
    }
    return out;
}

/** Cryptographically secure random bytes via the WebCrypto global — present
 * in both the Deno language sandbox (deno_runtime bundles deno_crypto) and
 * Node.js 20+ test environments. */
export function randomBytes(length: number): Uint8Array {
    const out = new Uint8Array(length);
    globalThis.crypto.getRandomValues(out);
    return out;
}

// ---------------------------------------------------------------------------
// X25519 key derivation
// ---------------------------------------------------------------------------

export interface X25519KeyPair {
    privateKey: Uint8Array;
    publicKey: Uint8Array;
}

/**
 * Derives a deterministic X25519 keypair from the agent's Ed25519 signing
 * capability. `signStringHex` should be `AgentAdapter.signStringHex` (or an
 * equivalent deterministic-signature function in tests) — see the module
 * doc comment above for why this is a sound substitute for a direct
 * Ed25519-to-X25519 scalar conversion when the raw private key is
 * unavailable.
 */
export function deriveX25519KeyPair(signStringHex: (payload: string) => string): X25519KeyPair {
    const signatureHex = signStringHex(X25519_SEED_MESSAGE);
    const signatureBytes = hexToBytes(signatureHex);
    const privateKey = sha256(signatureBytes); // 32 bytes — clamped internally by x25519.getPublicKey/getSharedSecret
    const publicKey = x25519.getPublicKey(privateKey);
    return { privateKey, publicKey };
}

// ---------------------------------------------------------------------------
// Room key sealing (X25519 ECDH + HKDF-SHA256 + AES-256-GCM)
// ---------------------------------------------------------------------------

/** Generates a fresh random 32-byte AES-256 room key. */
export function generateRoomKey(): Uint8Array {
    return randomBytes(AES_KEY_BYTES);
}

function deriveSealKey(sharedSecret: Uint8Array, ephemeralPublicKey: Uint8Array, recipientPublicKey: Uint8Array): Uint8Array {
    const salt = concatBytes(ephemeralPublicKey, recipientPublicKey);
    return hkdf(sha256, sharedSecret, salt, utf8ToBytes(ROOM_KEY_SEAL_INFO), AES_KEY_BYTES);
}

/**
 * Seals `roomKey` so that only the holder of `recipientPublicKey`'s
 * matching private key can recover it. Generates a fresh ephemeral X25519
 * keypair per call — sealing the same room key for the same recipient
 * twice produces different (but equivalent) envelopes.
 */
export function sealRoomKeyForRecipient(roomKey: Uint8Array, recipientPublicKey: Uint8Array): SealedRoomKeyEnvelope {
    const ephemeralPrivateKey = randomBytes(X25519_KEY_BYTES);
    const ephemeralPublicKey = x25519.getPublicKey(ephemeralPrivateKey);
    const sharedSecret = x25519.getSharedSecret(ephemeralPrivateKey, recipientPublicKey);
    const sealKey = deriveSealKey(sharedSecret, ephemeralPublicKey, recipientPublicKey);

    const nonce = randomBytes(AES_NONCE_BYTES);
    const ciphertext = gcm(sealKey, nonce).encrypt(roomKey);

    return {
        ephemeralPublicKey: bytesToHex(ephemeralPublicKey),
        nonce: bytesToHex(nonce),
        ciphertext: bytesToHex(ciphertext),
    };
}

/**
 * Opens a sealed room-key envelope using the recipient's own X25519
 * private key. Throws if the envelope was not sealed for this recipient
 * (AES-GCM auth tag mismatch) or is malformed.
 */
export function openRoomKeyEnvelope(envelope: SealedRoomKeyEnvelope, recipientPrivateKey: Uint8Array): Uint8Array {
    const ephemeralPublicKey = hexToBytes(envelope.ephemeralPublicKey);
    const nonce = hexToBytes(envelope.nonce);
    const ciphertext = hexToBytes(envelope.ciphertext);

    const recipientPublicKey = x25519.getPublicKey(recipientPrivateKey);
    const sharedSecret = x25519.getSharedSecret(recipientPrivateKey, ephemeralPublicKey);
    const sealKey = deriveSealKey(sharedSecret, ephemeralPublicKey, recipientPublicKey);

    return gcm(sealKey, nonce).decrypt(ciphertext);
}

// ---------------------------------------------------------------------------
// Key ring
// ---------------------------------------------------------------------------

/** Ordered map of key version → decrypted room key. */
export type KeyRing = Map<number, Uint8Array>;

export function buildKeyRing(
    entries: KeysResponseEntry[],
    recipientPrivateKey: Uint8Array,
): KeyRing {
    const ring: KeyRing = new Map();
    for (const entry of entries) {
        const plainKey = openRoomKeyEnvelope(entry.encryptedKey, recipientPrivateKey);
        ring.set(entry.version, plainKey);
    }
    return ring;
}

export function latestKeyVersion(ring: KeyRing): number {
    let max = 0;
    for (const v of ring.keys()) {
        if (v > max) max = v;
    }
    return max;
}

// ---------------------------------------------------------------------------
// Link expression encryption (room key, AES-256-GCM)
// ---------------------------------------------------------------------------

/**
 * `status` is optional on LinkExpression/WireLinkExpression. Spreading this
 * in (rather than always assigning `status: link.status`) keeps an absent
 * status truly absent from the reconstructed object instead of leaving a
 * `status: undefined` own-property behind — which would otherwise fail
 * strict deep-equality checks and any `"status" in link` guard elsewhere.
 */
export function statusField(status: string | undefined): { status?: string } {
    return status !== undefined ? { status } : {};
}

/**
 * Encrypts the entire LinkExpression (author, timestamp, proof, data) for
 * the wire. No metadata remains in cleartext — the server receives only
 * `{data: {ciphertext, nonce}, link_hash}`. The `link_hash` is a SHA-256
 * of the canonical plaintext fields, computed client-side so the server
 * can still content-address links for OR-Set dedup/removal matching
 * without seeing the plaintext.
 */
export function encryptLinkForWire(link: LinkExpression, roomKey: Uint8Array, keyVersion?: number): WireLinkExpression {
    const canonical = JSON.stringify({
        source: link.data.source,
        predicate: link.data.predicate ?? null,
        target: link.data.target,
        author: link.author,
        timestamp: link.timestamp,
    });
    const linkHashHex = bytesToHex(sha256(utf8ToBytes(canonical)));

    const fullPayload: Record<string, unknown> = {
        author: link.author,
        timestamp: link.timestamp,
        proof: link.proof,
        data: link.data,
    };
    if (link.status !== undefined) fullPayload.status = link.status;
    const plaintext = utf8ToBytes(JSON.stringify(fullPayload));
    const nonce = randomBytes(AES_NONCE_BYTES);
    const ciphertext = gcm(roomKey, nonce).encrypt(plaintext);

    return {
        data: { ciphertext: bytesToHex(ciphertext), nonce: bytesToHex(nonce) },
        link_hash: linkHashHex,
        ...(keyVersion !== undefined ? { key_version: keyVersion } : {}),
    };
}

/**
 * Reverses encryptLinkForWire. Handles both formats:
 * - Full encryption (current): ciphertext contains `{author, timestamp, proof, data}`
 * - Legacy data-only: ciphertext contains `{source, predicate, target}`
 * Throws if `roomKey` is wrong or the ciphertext was tampered with
 * (AES-GCM auth tag failure).
 */
export function decryptLinkFromWire(wireLink: WireLinkExpression, roomKeyOrRing: Uint8Array | KeyRing): LinkExpression {
    if (!isEncryptedLinkData(wireLink.data)) {
        throw new Error("decryptLinkFromWire: wire link has no encrypted data (expected {ciphertext, nonce} in data)");
    }
    let roomKey: Uint8Array;
    if (roomKeyOrRing instanceof Map) {
        const version = wireLink.key_version ?? 1;
        const key = roomKeyOrRing.get(version);
        if (!key) {
            throw new Error(
                `decryptLinkFromWire: no key for version ${version} in ring ` +
                `(have versions: ${[...roomKeyOrRing.keys()].join(", ")})`,
            );
        }
        roomKey = key;
    } else {
        roomKey = roomKeyOrRing;
    }
    const nonce = hexToBytes(wireLink.data.nonce);
    const ciphertext = hexToBytes(wireLink.data.ciphertext);
    const plaintext = gcm(roomKey, nonce).decrypt(ciphertext);
    const parsed = JSON.parse(bytesToUtf8(plaintext));

    if (parsed.author && parsed.data && typeof parsed.data === "object") {
        return {
            author: parsed.author,
            timestamp: parsed.timestamp,
            proof: parsed.proof,
            ...statusField(parsed.status),
            data: parsed.data as Link,
        };
    }

    return {
        author: wireLink.author ?? "",
        timestamp: wireLink.timestamp ?? "",
        proof: wireLink.proof ?? { signature: "", key: "" },
        ...statusField(wireLink.status),
        data: parsed as Link,
    };
}
