//! Route registry — maps every REST route to its request/response TypeScript types.
//!
//! Used by the `generate_route_map` test to produce `core/src/generated/rest/routes.ts`.

pub struct RouteEntry {
    pub method: &'static str,
    pub path: &'static str,
    pub request_type: &'static str,
    pub response_type: &'static str,
}

pub const ROUTES: &[RouteEntry] = &[
    // ── Agent ──
    RouteEntry { method: "GET",    path: "/agent",                          request_type: "never",                           response_type: "Agent" },
    RouteEntry { method: "GET",    path: "/agent/status",                   request_type: "never",                           response_type: "AgentStatus" },
    RouteEntry { method: "GET",    path: "/agent/is-locked",                request_type: "never",                           response_type: "boolean" },
    RouteEntry { method: "GET",    path: "/agent/apps",                     request_type: "never",                           response_type: "Apps[]" },
    RouteEntry { method: "GET",    path: "/agent/by-did/:did",              request_type: "never",                           response_type: "Agent | null" },
    RouteEntry { method: "PATCH",  path: "/agent/profile",                  request_type: "UpdateProfileRequest",            response_type: "Agent" },
    RouteEntry { method: "POST",   path: "/agent/generate",                 request_type: "GenerateAgentRequest",            response_type: "AgentStatus" },
    RouteEntry { method: "POST",   path: "/agent/import",                   request_type: "ImportAgentRequest",              response_type: "AgentStatus" },
    RouteEntry { method: "POST",   path: "/agent/lock",                     request_type: "LockAgentRequest",                response_type: "AgentStatus" },
    RouteEntry { method: "POST",   path: "/agent/unlock",                   request_type: "UnlockAgentRequest",              response_type: "AgentStatus" },
    RouteEntry { method: "POST",   path: "/agent/sign",                     request_type: "SignMessageRequest",              response_type: "AgentSignature" },
    RouteEntry { method: "DELETE",  path: "/agent/apps/:id",                request_type: "never",                           response_type: "Apps[]" },
    RouteEntry { method: "POST",   path: "/agent/auth/request",             request_type: "RequestCapabilityRequest",        response_type: "string" },
    RouteEntry { method: "POST",   path: "/agent/auth/permit",              request_type: "PermitCapabilityRequest",         response_type: "string" },
    RouteEntry { method: "POST",   path: "/agent/auth/jwt",                 request_type: "GenerateJwtRequest",              response_type: "string" },
    RouteEntry { method: "DELETE",  path: "/agent/auth/token/:token",       request_type: "never",                           response_type: "Apps[]" },
    RouteEntry { method: "GET",    path: "/agent/trusted",                  request_type: "never",                           response_type: "string[]" },
    RouteEntry { method: "PUT",    path: "/agent/trusted",                  request_type: "string[]",                        response_type: "string[]" },
    RouteEntry { method: "DELETE",  path: "/agent/trusted",                 request_type: "string[]",                        response_type: "string[]" },
    RouteEntry { method: "GET",    path: "/agent/entanglement-proofs",      request_type: "never",                           response_type: "EntanglementProof[]" },
    RouteEntry { method: "POST",   path: "/agent/entanglement-proofs",      request_type: "EntanglementProofInput[]",        response_type: "EntanglementProof[]" },
    RouteEntry { method: "DELETE",  path: "/agent/entanglement-proofs",     request_type: "EntanglementProofInput[]",        response_type: "EntanglementProof[]" },
    RouteEntry { method: "POST",   path: "/agent/entanglement-proof-preflight", request_type: "EntanglementProofPreflightRequest", response_type: "EntanglementProof" },

    // ── Languages ──
    RouteEntry { method: "GET",    path: "/languages",                      request_type: "never",                           response_type: "LanguageHandle[]" },
    RouteEntry { method: "POST",   path: "/languages/publish",              request_type: "PublishLanguageRequest",           response_type: "LanguageMeta" },
    RouteEntry { method: "POST",   path: "/languages/apply-template",       request_type: "ApplyTemplateRequest",            response_type: "LanguageRef" },
    RouteEntry { method: "GET",    path: "/languages/:address",             request_type: "never",                           response_type: "LanguageHandle" },
    RouteEntry { method: "DELETE",  path: "/languages/:address",            request_type: "never",                           response_type: "boolean" },
    RouteEntry { method: "GET",    path: "/languages/:address/meta",        request_type: "never",                           response_type: "LanguageMeta" },
    RouteEntry { method: "GET",    path: "/languages/:address/source",      request_type: "never",                           response_type: "string" },
    RouteEntry { method: "PUT",    path: "/languages/:address/settings",    request_type: "Record<string, unknown>",         response_type: "boolean" },

    // ── Perspectives ──
    RouteEntry { method: "GET",    path: "/perspectives",                   request_type: "never",                           response_type: "PerspectiveHandle[]" },
    RouteEntry { method: "POST",   path: "/perspectives",                   request_type: "CreatePerspectiveRequest",        response_type: "PerspectiveHandle" },
    RouteEntry { method: "GET",    path: "/perspectives/:uuid",             request_type: "never",                           response_type: "PerspectiveHandle" },
    RouteEntry { method: "PUT",    path: "/perspectives/:uuid",             request_type: "UpdatePerspectiveRequest",        response_type: "PerspectiveHandle" },
    RouteEntry { method: "DELETE",  path: "/perspectives/:uuid",            request_type: "never",                           response_type: "boolean" },
    RouteEntry { method: "GET",    path: "/perspectives/:uuid/snapshot",    request_type: "never",                           response_type: "Perspective" },
    RouteEntry { method: "POST",   path: "/perspectives/:uuid/publish-snapshot", request_type: "never",                      response_type: "string" },
    RouteEntry { method: "GET",    path: "/perspectives/:uuid/links",       request_type: "never",                           response_type: "DecoratedLinkExpression[]" },
    RouteEntry { method: "POST",   path: "/perspectives/:uuid/links",       request_type: "AddLinkRequest",                  response_type: "DecoratedLinkExpression" },
    RouteEntry { method: "PUT",    path: "/perspectives/:uuid/links",       request_type: "UpdateLinkRequest",               response_type: "DecoratedLinkExpression" },
    RouteEntry { method: "DELETE",  path: "/perspectives/:uuid/links",      request_type: "RemoveLinkRequest",               response_type: "boolean" },
    RouteEntry { method: "POST",   path: "/perspectives/:uuid/links/bulk",  request_type: "AddLinksBulkRequest",             response_type: "DecoratedLinkExpression[]" },
    RouteEntry { method: "POST",   path: "/perspectives/:uuid/links/remove-bulk", request_type: "RemoveLinksBulkRequest",    response_type: "DecoratedLinkExpression[]" },
    RouteEntry { method: "POST",   path: "/perspectives/:uuid/links/mutations", request_type: "LinkMutationsRequest",        response_type: "LinkMutationResponse" },
    RouteEntry { method: "POST",   path: "/perspectives/:uuid/links/expression", request_type: "AddLinkExpressionRequest",   response_type: "DecoratedLinkExpression" },
    RouteEntry { method: "POST",   path: "/perspectives/:uuid/query",       request_type: "QueryRequest",                    response_type: "unknown" },
    RouteEntry { method: "POST",   path: "/perspectives/:uuid/sdna",        request_type: "AddSdnaRequest",                  response_type: "boolean" },
    RouteEntry { method: "POST",   path: "/perspectives/:uuid/commands",    request_type: "ExecuteCommandsRequest",          response_type: "unknown" },
    RouteEntry { method: "POST",   path: "/perspectives/:uuid/batch",       request_type: "never",                           response_type: "string" },
    RouteEntry { method: "POST",   path: "/perspectives/:uuid/batch/commit", request_type: "CommitBatchRequest",             response_type: "LinkMutationResponse" },
    RouteEntry { method: "POST",   path: "/perspectives/:uuid/subscribe-query", request_type: "SubscribeQueryRequest",       response_type: "SubscribeQueryResponse" },
    RouteEntry { method: "POST",   path: "/perspectives/:uuid/subscribe-surreal-query", request_type: "SubscribeQueryRequest", response_type: "SubscribeQueryResponse" },
    RouteEntry { method: "POST",   path: "/perspectives/:uuid/keep-alive-query", request_type: "KeepAliveQueryRequest",      response_type: "boolean" },
    RouteEntry { method: "POST",   path: "/perspectives/:uuid/keep-alive-surreal-query", request_type: "KeepAliveQueryRequest", response_type: "boolean" },
    RouteEntry { method: "POST",   path: "/perspectives/:uuid/dispose-query-subscription", request_type: "DisposeQueryRequest", response_type: "boolean" },
    RouteEntry { method: "POST",   path: "/perspectives/:uuid/dispose-surreal-query-subscription", request_type: "DisposeQueryRequest", response_type: "boolean" },
    RouteEntry { method: "POST",   path: "/perspectives/:uuid/create-subject", request_type: "CreateSubjectRequest",         response_type: "boolean" },
    RouteEntry { method: "POST",   path: "/perspectives/:uuid/get-subject-data", request_type: "GetSubjectDataRequest",      response_type: "string" },

    // ── Neighbourhoods ──
    RouteEntry { method: "POST",   path: "/neighbourhoods/join",            request_type: "JoinNeighbourhoodRequest",        response_type: "PerspectiveHandle" },
    RouteEntry { method: "POST",   path: "/neighbourhoods/publish",         request_type: "PublishNeighbourhoodRequest",      response_type: "string" },
    RouteEntry { method: "POST",   path: "/neighbourhoods/:uuid/broadcast", request_type: "BroadcastRequest",                response_type: "boolean" },
    RouteEntry { method: "POST",   path: "/neighbourhoods/:uuid/signal",    request_type: "SignalRequest",                    response_type: "boolean" },
    RouteEntry { method: "PUT",    path: "/neighbourhoods/:uuid/online-status", request_type: "SetOnlineStatusRequest",       response_type: "boolean" },
    RouteEntry { method: "GET",    path: "/neighbourhoods/:uuid/online-agents", request_type: "never",                        response_type: "OnlineAgent[]" },
    RouteEntry { method: "GET",    path: "/neighbourhoods/:uuid/other-agents",  request_type: "never",                        response_type: "string[]" },
    RouteEntry { method: "GET",    path: "/neighbourhoods/:uuid/has-telepresence", request_type: "never",                     response_type: "boolean" },

    // ── Expressions ──
    RouteEntry { method: "POST",   path: "/expressions",                    request_type: "CreateExpressionRequest",          response_type: "string" },
    RouteEntry { method: "POST",   path: "/expressions/many",               request_type: "ExpressionManyRequest",            response_type: "Array<unknown | null>" },
    RouteEntry { method: "GET",    path: "/expressions/:url",               request_type: "never",                           response_type: "unknown | null" },
    RouteEntry { method: "GET",    path: "/expressions/:url/interactions",  request_type: "never",                           response_type: "InteractionMeta[]" },
    RouteEntry { method: "POST",   path: "/expressions/:url/interact",      request_type: "InteractionCall",                  response_type: "string" },

    // ── Runtime ──
    RouteEntry { method: "GET",    path: "/runtime/info",                   request_type: "never",                           response_type: "RuntimeInfo" },
    RouteEntry { method: "POST",   path: "/runtime/quit",                   request_type: "never",                           response_type: "boolean" },
    RouteEntry { method: "PUT",    path: "/runtime/status",                 request_type: "SetStatusRequest",                response_type: "boolean" },
    RouteEntry { method: "POST",   path: "/runtime/open-link",              request_type: "OpenLinkRequest",                 response_type: "boolean" },
    RouteEntry { method: "POST",   path: "/runtime/export",                 request_type: "ExportRequest",                   response_type: "boolean" },
    RouteEntry { method: "POST",   path: "/runtime/import",                 request_type: "ImportRequest",                   response_type: "unknown" },
    RouteEntry { method: "GET",    path: "/runtime/tls-domain",             request_type: "never",                           response_type: "string | null" },
    RouteEntry { method: "GET",    path: "/runtime/compute-log",            request_type: "never",                           response_type: "unknown" },
    RouteEntry { method: "POST",   path: "/runtime/holochain/restart",      request_type: "never",                           response_type: "boolean" },
    RouteEntry { method: "POST",   path: "/runtime/verify-signature",       request_type: "VerifySignatureRequest",          response_type: "boolean" },
    RouteEntry { method: "GET",    path: "/runtime/friends",                request_type: "never",                           response_type: "string[]" },
    RouteEntry { method: "PUT",    path: "/runtime/friends",                request_type: "FriendsListRequest",              response_type: "string[]" },
    RouteEntry { method: "DELETE",  path: "/runtime/friends",               request_type: "FriendsListRequest",              response_type: "string[]" },
    RouteEntry { method: "GET",    path: "/runtime/friends/:did",           request_type: "never",                           response_type: "unknown" },
    RouteEntry { method: "POST",   path: "/runtime/friends/:did/message",   request_type: "FriendSendMessageRequest",        response_type: "boolean" },
    RouteEntry { method: "GET",    path: "/runtime/messages/inbox",         request_type: "never",                           response_type: "unknown" },
    RouteEntry { method: "GET",    path: "/runtime/messages/outbox",        request_type: "never",                           response_type: "unknown" },
    RouteEntry { method: "GET",    path: "/runtime/notifications",          request_type: "never",                           response_type: "Notification[]" },
    RouteEntry { method: "POST",   path: "/runtime/notifications",          request_type: "NotificationInput",               response_type: "boolean" },
    RouteEntry { method: "PATCH",  path: "/runtime/notifications/:id",      request_type: "NotificationInput",               response_type: "boolean" },
    RouteEntry { method: "DELETE",  path: "/runtime/notifications/:id",     request_type: "never",                           response_type: "boolean" },
    RouteEntry { method: "GET",    path: "/runtime/link-language-templates", request_type: "never",                           response_type: "string[]" },
    RouteEntry { method: "PUT",    path: "/runtime/link-language-templates", request_type: "LinkLanguageTemplatesRequest",    response_type: "string[]" },
    RouteEntry { method: "DELETE",  path: "/runtime/link-language-templates", request_type: "LinkLanguageTemplatesRequest",   response_type: "string[]" },
    RouteEntry { method: "GET",    path: "/runtime/hc/agent-infos",         request_type: "never",                           response_type: "string[]" },
    RouteEntry { method: "POST",   path: "/runtime/hc/agent-infos",         request_type: "AddAgentInfosRequest",            response_type: "boolean" },
    RouteEntry { method: "GET",    path: "/runtime/network-metrics",        request_type: "never",                           response_type: "string" },
    RouteEntry { method: "GET",    path: "/runtime/free-hosting-enabled",   request_type: "never",                           response_type: "boolean" },
    RouteEntry { method: "PUT",    path: "/runtime/free-hosting-enabled",   request_type: "Record<string, unknown>",         response_type: "boolean" },

    // ── Users ──
    RouteEntry { method: "GET",    path: "/users/multi-user-enabled",       request_type: "never",                           response_type: "boolean" },
    RouteEntry { method: "PUT",    path: "/users/multi-user-enabled",       request_type: "SetMultiUserRequest",             response_type: "boolean" },
    RouteEntry { method: "GET",    path: "/users",                          request_type: "never",                           response_type: "unknown" },
    RouteEntry { method: "POST",   path: "/users",                          request_type: "CreateUserRequest",               response_type: "unknown" },
    RouteEntry { method: "GET",    path: "/users/:email/wallet",            request_type: "never",                           response_type: "string" },
    RouteEntry { method: "POST",   path: "/users/login",                    request_type: "LoginUserRequest",                response_type: "unknown" },
    RouteEntry { method: "POST",   path: "/users/verify-email",             request_type: "VerifyEmailRequest",              response_type: "unknown" },
    RouteEntry { method: "POST",   path: "/users/request-verification",     request_type: "RequestVerificationRequest",      response_type: "unknown" },
    RouteEntry { method: "POST",   path: "/dev/email-test",                 request_type: "EmailTestRequest",                response_type: "unknown" },

    // ── Hosting ──
    RouteEntry { method: "GET",    path: "/hosting",                        request_type: "never",                           response_type: "HostingInfoResponse" },
    RouteEntry { method: "GET",    path: "/hosting/wallet",                 request_type: "never",                           response_type: "HostingWalletResponse" },
    RouteEntry { method: "GET",    path: "/hosting/wallet/history",         request_type: "never",                           response_type: "unknown" },
    RouteEntry { method: "PUT",    path: "/hosting/wallet/hot-wallet-address", request_type: "SetHotWalletAddressRequest",   response_type: "boolean" },
    RouteEntry { method: "POST",   path: "/hosting/request-payment",        request_type: "RequestPaymentRequest",           response_type: "unknown" },

    // ── AI ──
    RouteEntry { method: "GET",    path: "/ai/models",                      request_type: "never",                           response_type: "Model[]" },
    RouteEntry { method: "POST",   path: "/ai/models",                      request_type: "Record<string, unknown>",         response_type: "string" },
    RouteEntry { method: "PUT",    path: "/ai/models/:id",                  request_type: "Record<string, unknown>",         response_type: "boolean" },
    RouteEntry { method: "DELETE",  path: "/ai/models/:id",                 request_type: "never",                           response_type: "boolean" },
    RouteEntry { method: "PUT",    path: "/ai/models/:id/default",          request_type: "SetDefaultModelRequest",          response_type: "boolean" },
    RouteEntry { method: "GET",    path: "/ai/models/default",              request_type: "never",                           response_type: "Model | null" },
    RouteEntry { method: "GET",    path: "/ai/model-loading-status",        request_type: "never",                           response_type: "unknown" },
    RouteEntry { method: "GET",    path: "/ai/tasks",                       request_type: "never",                           response_type: "AITask[]" },
    RouteEntry { method: "POST",   path: "/ai/tasks",                       request_type: "Record<string, unknown>",         response_type: "AITask" },
    RouteEntry { method: "PUT",    path: "/ai/tasks/:id",                   request_type: "Record<string, unknown>",         response_type: "AITask" },
    RouteEntry { method: "DELETE",  path: "/ai/tasks/:id",                  request_type: "never",                           response_type: "boolean" },
    RouteEntry { method: "POST",   path: "/ai/prompt",                      request_type: "PromptRequest",                   response_type: "string" },
    RouteEntry { method: "POST",   path: "/ai/embed",                       request_type: "EmbedRequest",                    response_type: "string" },
    RouteEntry { method: "POST",   path: "/ai/transcription/open",          request_type: "OpenTranscriptionRequest",        response_type: "string" },
    RouteEntry { method: "POST",   path: "/ai/transcription/feed",          request_type: "FeedTranscriptionRequest",        response_type: "string" },
    RouteEntry { method: "POST",   path: "/ai/transcription/close",         request_type: "CloseTranscriptionRequest",       response_type: "string" },

    // ── SSE Events (response is void — these are streaming endpoints) ──
    RouteEntry { method: "GET",    path: "/events/agent",                   request_type: "never",                           response_type: "void" },
    RouteEntry { method: "GET",    path: "/events/perspectives",            request_type: "never",                           response_type: "void" },
    RouteEntry { method: "GET",    path: "/events/perspectives/:uuid/links", request_type: "never",                          response_type: "void" },
    RouteEntry { method: "GET",    path: "/events/neighbourhoods/:uuid/signals", request_type: "never",                      response_type: "void" },
    RouteEntry { method: "GET",    path: "/events/runtime",                 request_type: "never",                           response_type: "void" },
    RouteEntry { method: "GET",    path: "/events/ai",                      request_type: "never",                           response_type: "void" },
    RouteEntry { method: "GET",    path: "/events/unified",                 request_type: "never",                           response_type: "void" },

    // ── WebSocket ──
    RouteEntry { method: "GET",    path: "/ws/audio",                       request_type: "never",                           response_type: "void" },
];
