export type CallZomeResponseGeneric<Payload> = Payload;
/**
 * @public
 */
export type CallZomeResponse = CallZomeResponseGeneric<any>;

export type HoloHash = Uint8Array;
export type AgentPubKey = HoloHash;
export type InstalledAppId = string;
export type NetworkSeed = string;
export type MembraneProof = Uint8Array;
export type DnaHash = HoloHash;
export type RoleName = string;
export type Timestamp = number;
export type CellId = [DnaHash, AgentPubKey];
export enum CellType {
    Provisioned = "provisioned",
    Cloned = "cloned",
    Stem = "stem",
  }
  export type DnaModifiers = {
    network_seed: NetworkSeed;
    properties: Uint8Array;
  };
  export interface ProvisionedCell {
    cell_id: CellId;
    dna_modifiers: DnaModifiers;
    name: string;
  }
  export interface ClonedCell {
    cell_id: CellId;
    clone_id: RoleName;
    original_dna_hash: DnaHash;
    dna_modifiers: DnaModifiers;
    name: string;
    enabled: boolean;
  }
  
  export interface StemCell {
    dna: DnaHash;
    name?: string;
    dna_modifiers: DnaModifiers;
  }
  export type CellInfo =
    | {
        type: CellType.Provisioned;
        value: ProvisionedCell;
      }
    | {
        type: CellType.Cloned;
        value: ClonedCell;
      }
    | {
        type: CellType.Stem;
        value: StemCell;
      };
      export type PausedAppReason = {
        type: "error";
        value: string;
      };
      
      /**
       * @public
       */
      export type DisabledAppReason =
        | { type: "never_started" }
        | { type: "user" }
        | { type: "not_started_after_providing_memproofs" }
        | {
            type: "error";
            value: string;
          };
      
      /**
       * @public
       */
      export type AppInfoStatus =
        | {
            type: "paused";
            value: { reason: PausedAppReason };
          }
        | {
            type: "disabled";
            value: {
              reason: DisabledAppReason;
            };
          }
        | { type: "awaiting_memproofs" }
        | { type: "running" };

export type AppInfo = {
    agent_pub_key: AgentPubKey;
    installed_app_id: InstalledAppId;
    cell_info: Record<RoleName, Array<CellInfo>>;
    status: AppInfoStatus;
    installed_at: Timestamp;
  };

export type AppBundleSource = {
    type: "path";
    value: string;
} | {
    type: "bytes";
    value: Uint8Array;
};

export type RoleSettingsMap = {
    [key: RoleName]: RoleSettings;
};
export type YamlProperties = unknown;
export type DnaModifiersOpt = {
    network_seed?: NetworkSeed;
    properties?: YamlProperties;
};
export type RoleSettings = {
    type: "use_existing";
    value: {
        cell_id: CellId;
    };
} | {
    type: "provisioned";
    value: {
        membrane_proof?: MembraneProof;
        modifiers?: DnaModifiersOpt;
    };
};
export type Signature = Uint8Array;

export type InstallAppRequest = {
    /**
     * Where to obtain the AppBundle, which contains the app manifest and DNA bundles
     * to be installed. This is the main payload of app installation.
     */
    source: AppBundleSource;
    /**
     * The agent to use when creating Cells for this App.
     * If not specified, a new agent will be generated by Holochain.
     * If DPKI is enabled (default), and the agent key is not specified here,
     * a new agent key will be derived from the DPKI device seed and registered with DPKI.
     */
    agent_key?: AgentPubKey;
    /**
     * The unique identifier for an installed app in this conductor.
     * If not specified, it will be derived from the app name in the bundle manifest.
     */
    installed_app_id?: InstalledAppId;
    /**
     * Optional global network seed override.  If set will override the network seed value for all
     * DNAs in the bundle.
     */
    network_seed?: NetworkSeed;
    /**
     * Specify role specific settings or modifiers that will override any settings in the dna manifest.
     */
    roles_settings?: RoleSettingsMap;
    /**
     * Optional: If app installation fails due to genesis failure, normally the app will be immediately uninstalled.
     * When this flag is set, the app is left installed with empty cells intact. This can be useful for
     * using graft_records_onto_source_chain, or for diagnostics.
     */
    ignore_genesis_failure?: boolean;
};