name: "release"
on:
  push:
    tags:
      - 'v*'

jobs:
  publish-tauri:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-10.15, ubuntu-latest, windows-2019]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: install app dependencies and info
        run: yarn install && yarn run tauri info
      - name: download Linux & MacOS ad4m-host
        run: ./scripts/setup-binaries.sh
      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf
      - name: download Windows ad4m-host
        if: matrix.platform == 'windows-2019'
        shell: bash
        run: |
          mkdir src-tauri/bins
          cd src-tauri/bins
          curl -vLJ https://github.com/perspect3vism/ad4m-host/releases/download/v0.0.32-fix6/ad4m-windows-x64-node-16.x.exe --output ad4m-x86_64-pc-windows-gnu.exe
          curl -vLJ https://github.com/perspect3vism/ad4m-host/releases/download/v0.0.32-fix6/ad4m-windows-x64-node-16.x.exe --output ad4m-x86_64-pc-windows-msvc.exe
      - name: build the app
        run: yarn run build-all
        env:
         CI: ""
      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
          releaseName: "Ad4min v__VERSION__"
          releaseBody: "See the assets to download this version and install."
