// Residual lazy-loaded ESM / JS sources for the AD4M custom Deno snapshot.
//
// deno 2.9 does NOT embed unconsumed `lazy_loaded_esm` / `lazy_loaded_js`
// sources (e.g. `node:buffer`) into the V8 snapshot blob — the snapshot
// only records the specifier list. At runtime,
// `add_residual_lazy_loaded_sources` populates the module map from the
// `WorkerOptions.residual_lazy_{esm,js}_sources` slices; if those are
// empty, `take_lazy_esm_source("node:buffer")` returns None and any
// `import { Buffer } from "node:buffer"` fails through to the custom
// ModuleLoader, which correctly returns NotFound (it doesn't own `node:*`).
//
// The two `include!(...)` files below are generated by
// `rust-executor/src/bin/generate_snapshot.rs` after each snapshot build.
// They live next to the snapshot binary (at the workspace root) and are
// listed in the workspace's `.gitignore` because they must be regenerated
// whenever the snapshot changes.

// Fallback empty tables — used when the residual files haven't been
// generated yet (e.g. clean checkout before first `generate_snapshot`
// run). Cargo `include!` errors on missing files, so we do a compile-time
// existence check via `cfg_attr` on a companion build-script-created
// marker isn't practical here; the simplest robust path is to keep the
// generator writing the files to a fixed location and to include them
// unconditionally. If the files don't exist yet, the build breaks with a
// clear "file not found" pointing at CUSTOM_DENO_SNAPSHOT.residual_esm.rs.
// Paths are relative to THIS file. The generator (`bin/generate_snapshot.rs`)
// is always executed from the `rust-executor/` package dir (that's cwd for
// `cargo run -p ad4m-executor --bin generate_snapshot`), so the files land
// two levels up from here: `rust-executor/CUSTOM_DENO_SNAPSHOT.residual_*.rs`.
include!("../../CUSTOM_DENO_SNAPSHOT.residual_esm.rs");
include!("../../CUSTOM_DENO_SNAPSHOT.residual_js.rs");
