query AgentStatus {
    agentStatus {
        isInitialized
        isUnlocked
        did
        didDocument
        error
    }
}

mutation RequestCapability($appName: String!, $appDesc: String!, $appUrl: String!, $capabilities: String!) {
    agentRequestCapability(appName: $appName, appDesc: $appDesc, appUrl: $appUrl, capabilities: $capabilities)
}