query ByFilter($filter: String!) {
    languages(filter: $filter) {
        name
        address
        settings
    }
}

query ByAddress($address: String!) {
    language(address: $address) {
        name
        address
        settings
    }
}

mutation WriteSettings($languageAddress: String!, $settings: String!) {
    languageWriteSettings(languageAddress: $languageAddress, settings: $settings)
}