query All {
    perspectives {
        uuid
        name
        sharedUrl
        neighbourhood { 
            linkLanguage 
            meta { 
                links
                    {
                        author
                        timestamp
                        data { source, predicate, target }
                        proof { valid, invalid, signature, key }
                    }  
            } 
        }
    }
    
}