query Info {
    runtimeInfo {
        ad4mExecutorVersion,
        isInitialized,
        isUnlocked
    }
}

mutation Quit { runtimeQuit }

mutation AddTrustedAgents($agents: [String!]!) {
    addTrustedAgents(agents: $agents)
}

mutation DeleteTrustedAgents($agents: [String!]!) {
    deleteTrustedAgents(agents: $agents)
}

query TrustedAgents {
    getTrustedAgents
}

query LinkLanguageTemplates {
    runtimeKnownLinkLanguageTemplates
}

mutation AddLinkLanguageTemplates($addresses: [String!]!) {
    runtimeAddKnownLinkLanguageTemplates(addresses: $addresses)
}

mutation RemoveLinkLanguageTemplates($addresses: [String!]!) {
    runtimeRemoveKnownLinkLanguageTemplates(addresses: $addresses)
}