query Info {
    runtimeInfo {
        ad4mExecutorVersion,
        isInitialized,
        isUnlocked
    }
}

mutation Quit { runtimeQuit }

mutation AddTrustedAgents($agents: [String!]!) {
    addTrustedAgents(agents: $agents)
}

mutation DeleteTrustedAgents($agents: [String!]!) {
    deleteTrustedAgents(agents: $agents)
}

query TrustedAgents {
    getTrustedAgents
}